config/routes.rb
Family::Application.routes.draw do

  root :to => 'fathers#index'

  resources :fathers

end

app/models/father.rb
class Father < ActiveRecord::Base
  attr_accessible :name, :parent_id
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  # GET /fathers
  # GET /fathers.json
  def index
    @fathers = Father.scoped
    @father = Father.new
  end


  def show
    @father = Father.find(params[:id])
  end


  def new
    @father = Father.new(:parent_id => params[:parent_id])
  end


  def create
    @father = Father.new(params[:father])
    if @father.save
        redirect_to fathers_path
    else
        render :new
    end
  end


  def destroy
    @father = Father.find(params[:id])
    @father.destroy
    redirect_to fathers_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fathers_helper.rb
module FathersHelper
  def nested_family(fathers)
    fathers.map do |father, sons|
      render(father) + content_tag(:div, nested_family(sons), :class => "nested_family")
    end.join.html_safe
  end
end

app/views/fathers/_father.html.erb
<div class="father">

    <b><%= father.name %>:</b>
    <%= link_to "Add Son", new_father_path(:parent_id => father) %> |
    <%= link_to "Destroy", father, method: :delete, data: "Are you sure?" %>

</div>

app/views/fathers/_form.html.erb
<%= form_for @father do |f| %>

  <%= f.hidden_field :parent_id %>
  <p>
    <%= f.label :name, "New Father" %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit "Create Father" %></p>
<% end %>

app/views/fathers/edit.html.erb
<h1>Editing Father</h1>

<%= render 'form' %>

<%= link_to 'Show', @father %> |
<%= link_to 'Back', fathers_path %>

app/views/fathers/index.html.erb
<h1> Fathers and Sons </h1>

<%= nested_family @fathers.arrange(:order => :created_at) %>

<%= render "form" %>

app/views/fathers/new.html.erb
<h1>New Son</h1>

<%= render @father.parent if @father.parent %>

<%= form_for @father do |f| %>

  <%= f.hidden_field :parent_id %>
  <p>
    <%= f.label :name, "New Son" %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit "Create Son" %></p>
<% end %>

<%= link_to 'Back', fathers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Family</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>